### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by griffin-stewie** [tcarlsen/atom-message-panel#66]
[Enter steps to reproduce below:]

1. show atom-message-panel with LineMessageView
2. click preview 

I think there is not `atom.project.rootDirectory` now.

**Atom Version**: 0.180.0
**System**: Mac OS X 10.10.2
**Thrown From**: [redpen](https://github.com/griffin-stewie/atom-redpen) package, v0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/foo/foo_dev/Atom/redpen-atom/node_modules/atom-message-panel/lib/LineMessageView.js:51

TypeError: Cannot read property 'path' of undefined
  at [object Object].LineMessageView.goToLine (/Users/foo/foo_dev/Atom/redpen-atom/node_modules/atom-message-panel/lib/LineMessageView.js:51:58)
  at HTMLPreElement.<anonymous> (/Users/foo/foo_dev/Atom/redpen-atom/node_modules/atom-message-panel/node_modules/space-pen/lib/space-pen.js:214:36)
  at HTMLPreElement.jQuery.event.dispatch (/Users/foo/foo_dev/Atom/redpen-atom/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLPreElement.elemData.handle (/Users/foo/foo_dev/Atom/redpen-atom/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -0:04.0 redpen:validate (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "term",
      "markdown-table-formatter",
      "markdown-pdf",
      "plantuml-preview",
      "autocomplete-plus"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "redpen": {
    "pathForRedPen": "/usr/local/bin/redpen",
    "JAVA_HOME": "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
asciidoc-preview, v0.4.2
asciidoctor-preview, v0.1.0
atom-color-highlight, v3.0.8
bracket-matcher, v0.71.0
file-icons, v1.4.11
git-log, v0.2.0
go-plus, v3.2.2
japanese-wrap, v0.2.3
jsonlint, v1.0.1
language-asciidoc, v0.11.1
language-lua, v0.9.0
linter-coffeelint, v0.1.7
linter-lua, v0.1.3
linter-shellcheck, v0.0.6
pretty-json, v0.3.2
recent-files, v0.3.0
redpen, v0.2.1
regex-railroad-diagram, v0.6.3
save-session, vundefined
svg-preview, v0.5.1
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

**Comment by griffin-stewie** [comment]
additional info.

my another mac had Atom v0.179.0.
It worked.

However I updated Atom to v0.180.0 (latest version this time), 
then this error has occurred.

thx

**Comment by tcarlsen** [comment]
was just about to say that I couldn't reproduce your error, but that explains alot

**Comment by basarat** [comment]
Same here 
![image](https://cloud.githubusercontent.com/assets/874898/6259140/96e772ac-b823-11e4-8deb-aa48ba0602ce.png)

**Comment by basarat** [comment]
`atom.project.rootDirectory` is no more. 

RootDirectories exists. 

![image](https://cloud.githubusercontent.com/assets/874898/6259171/b6f86a38-b823-11e4-9d95-251761437b40.png)

**Comment by tcarlsen** [comment]
`1.2.2`is out with a fix

**Comment by griffin-stewie** [comment]
Thank you @tcarlsen 
It works!
:+1:
